### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by Dmry** [SCM-NV/PLAMS#102]
The latest version is more than two years old and is missing interfaces that are included in the documentation on your website. Would it, perhaps, be time to tag a new version? I guess that should also allow users to access all the documented interfaces when installing with pip.

**Comment by muhrin** [comment]
I would second this request.  We have a project that currently has to refer to this github repo in the `setup.py` to get the requirements.  It would be much more convenient (and more clean if things here change) to be able to specify a release version to be pulled from pypi.

Are there any plans to issue a release?

**Comment by patrickmelix** [comment]
In the Dev-Mattermost of SCM @mirkofranchini stated that it is on his todo list... They were busy with the new release, I guess it should be coming up soonish.

**Comment by muhrin** [comment]
Fantastic, thanks for the update. I think this would really help users of the library as I suspect the most common way to install is still via `pypi`.

**Comment by mirkofranchini** [comment]
PLAMS 1.5.1 is now on pypi https://pypi.org/project/plams/ !!
