### ISSUE TITLE
Syntax errors in `crystal.py`

### ISSUE THREAD

**Issue by muhrin** [SCM-NV/PLAMS#107]
The crystal plugin code has a bunch of syntax erros with incorrect use of comparison operators.  In python 3.8+ you will get warnings such as this:

```
...python3.8/site-packages/scm/plams/interfaces/adfsuite/scmjob.py:310: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif value is '' or value is True:
...python3.8/site-packages/scm/plams/interfaces/thirdparty/cp2k.py:479: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif value is '' or value is True:
...python3.8/site-packages/scm/plams/interfaces/thirdparty/crystal.py:112: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not key is '':
...python3.8/site-packages/scm/plams/interfaces/thirdparty/crystal.py:117: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif key is '':
...site-packages/scm/plams/interfaces/thirdparty/crystal.py:120: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif value is '' or value is True:
```

This should be changed following the advice in the warninig i.e. when doing value comparison (as opposed to reference comparison) one should use the boolean operators.  This may or may not lead to actual faults in the code.

**Comment by patrickmelix** [comment]
That is most likely my fault. Do you want to correct all those or should I?

**Comment by muhrin** [comment]
Hi Patrick,

thanks a lot for the quick reply.  No worries, I can put together a quick PR.
