### ISSUE TITLE
typos in https://www.scm.com/doc/plams/interfaces/cp2k.html

### ISSUE THREAD

**Issue by houzf** [SCM-NV/PLAMS#115]
As for the example of Setting written in the documents of PLAMS: https://www.scm.com/doc/plams/interfaces/cp2k.html, there are some typoes. This example isn't compatible with the latest version (e.g., 9.1) of cp2k.
1. ----------------
penta.input.force_eval.subsys.kind.C.basis_set = "GTH-PBE-Q4"
penta.input.force_eval.subsys.kind.H.basis_set = "GTH-PBE-q1"
--------------->
penta.input.force_eval.subsys.kind.C.potential = "GTH-PBE-Q4"
penta.input.force_eval.subsys.kind.H.potential = "GTH-PBE-q1"

2. -------------
penta.input.['global'].print_level = "low"
penta.input.['global'].project  = "example"
penta.input.['global'].run_type = "energy_force"
--------------->
penta.input['global'].print_level = "low"
penta.input['global'].project  = "example"
penta.input['global'].run_type = "energy_force"

3.------------
penta.input.force_eval.subsys.cell.A = [16.11886919, 0.07814137, -0.697284243]
penta.input.force_eval.subsys.cell.B = [-0.215317662, 4.389405268, 1.408951791]
penta.input.force_eval.subsys.cell.C = [-0.216126961, 1.732808365, 9.74896108]
------------->
penta.input.force_eval.subsys.cell.A = '16.11886919  0.07814137  -0.697284243'
penta.input.force_eval.subsys.cell.B = '-0.215317662 4.389405268  1.408951791'
penta.input.force_eval.subsys.cell.C = '-0.216126961  1.732808365  9.74896108'

4------------
penta.input.force_eval.qs.method = "GPW"
penta.input.force_eval.scf.eps_scf = 1e-6
penta.input.force_eval.scf.max_scf = 200
penta.input.force_eval.xc.xc_functional = "PBE"
-------------->
penta.input.force_eval.dft.qs.method = "GPW"
penta.input.force_eval.dft.scf.eps_scf = 1e-6
penta.input.force_eval.dft.scf.max_scf = 200
penta.input.force_eval.dft.xc['&xc_functional'] = "PBE \n  &END"

**Comment by patrickmelix** [comment]
I agree on everything except ` penta.input.force_eval.dft.xc['&xc_functional'] = "PBE \n &END"`, which I would make ` penta.input.force_eval.xc.xc_functional._h = "PBE"` just because it is nicer ;-)

Created MR #116.

**Comment by houzf** [comment]
Thank you very much for your suggestions.

**Comment by robertrueger** [comment]
Thanks for fixing, Patrick! Merged your PR.
