### ISSUE TITLE
Feature improvement: get_energy_landscape to retrieve state vibrational frequencies

### ISSUE THREAD

**Issue by lopeztarifa** [SCM-NV/PLAMS#124]
Dear SCM developers, 

I was wondering if the function [get_energy_landscape](https://github.com/SCM-NV/PLAMS/blob/41d2e30a264844da30cd3a7cd01650d5698234b6/interfaces/adfsuite/ams.py#L1481) could be improved so there is an easy (method state.frequencies?) to access the vibrational frequencies of each state. 

So far I managed to get them by looping the get_frequencies function on the states, but it is annoying as I have to select the right file name for the engine argument. I hope you can improve it. 

Thanks,

**Comment by nfaguirrec** [comment]
Dear @lopeztarifa,

I'll take a look at it!

Best,
Nestor
