### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by Dmry** [SCM-NV/PLAMS#127]
Hi SCM,

Would you guys be willing to tag a new PLAMS version? The current one on here and PyPi is about to be two years old now.

**Comment by YHordijk** [comment]
Any updates on this? It would be nice to be able to use the new `plams.init` function with the `use_existing_folder` argument.

**Comment by dormrod** [comment]
Version 2024.103 has been tagged and added to PyPI. This aligns with the AMS 2024.103 release.
