### ISSUE TITLE
Job names starting with '-' will result in grep_output() failing

### ISSUE THREAD

**Issue by patrickmelix** [SCM-NV/PLAMS#14]
**Steps to reproduce:**
Name a job '-something', run, try to do `job.results.grep_output('some string')`.
**Resulting error:** 
> grep: invalid option -- '.'

**Proposed fix:**
```
diff --git a/src/scm/plams/core/results.py b/src/scm/plams/core/results.py
index 485b9d3..f3c782a 100644
--- a/src/scm/plams/core/results.py
+++ b/src/scm/plams/core/results.py
@@ -358,7 +358,7 @@ class Results(object):
         filename = filename.replace('$JN', self.job.name)
         if filename in self.files:
             try:
-                output = subprocess.check_output(command + [filename], cwd=self.job.path)
+                output = subprocess.check_output(command + ['./'+filename], cwd=self.job.path)
             except subprocess.CalledProcessError:
                 return []
             output = string(output)
```

**Comment by h4nsu** [comment]
Proposed fix: stop using stupid jobnames? :P

**Comment by patrickmelix** [comment]
Well, if you post that joke on me it is time to assign someone to fix this is a nicer way... You wanted it ;-)

**Comment by h4nsu** [comment]
I really mean it. It's generally a good practice to use identifiers starting with a letter pretty much everywhere (programming, filesystem etc.). I'll put a big red warning in the docs stating that job name has to start with a letter.
