### ISSUE TITLE
Molecule Property Charge is not Propagated to Jobs

### ISSUE THREAD

**Issue by patrickmelix** [SCM-NV/PLAMS#151]
Even though there's mention of a `Molecule.properties.charge` in some places, the Molecules properties have no effect on `AMSJob` system setup. Is this intentional or is it just missing in the input parser?

**Comment by dormrod** [comment]
Do you have a small example of the behaviour you mean? The charge should be serialised into the system block of the job, for example:
```
mol = Molecule()
mol.add_atom(Atom(symbol="H", coords=(0, 0, 0)))
mol.properties.charge = 1
job = AMSJob(mol)
print(job.get_input())

System
  Atoms
              H       0.0000000000       0.0000000000       0.0000000000
  End
  Charge 1
End
```

**Comment by patrickmelix** [comment]
Ouch, my mistake. Sorry for the spam....
