### ISSUE TITLE
Atom names are lost upon serializing/deserializing molecule

### ISSUE THREAD

**Issue by ridderl** [SCM-NV/PLAMS#17]
```
mol[1].name = 'test'
mol_new = plams.Molecule.from_dict(**mol.as_dict())
mol_new[1].name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Atom' object has no attribute 'name'
```

**Comment by h4nsu** [comment]
Sorry, guys, this is your code, I never really read or used it... But now when I look at it, it clearly does not preserve "regular" python attributes like `name` in the example above. The solution would be to put all such attributes inside `properties` dict. Or refactor JSON <-> Molecule interface.

BTW, this code:
```def get_bond_order(bond):
    if bond.order:
        return bond.order
    elif bond.AR:
        return bond.AR
    else:
        msg = "bond does not contain order attribute"
        raise AttributeError(msg)```
does not make any sense...

**Comment by ridderl** [comment]
I tried to fix the serialization by a nested dict in this commit: 6596ba4e4fee6430624e61ef122b9346575d1047
Do you think it is OK like that?

**Comment by h4nsu** [comment]
@ridderl:
Your solution works fine, but I just dicovered that it suffers from the same problem we encountered with ``Molecule.copy()``. If your molecule is too big and contains bonds, ``deepcopy`` (in ``mol_dict = copy.deepcopy(self.__dict__)``) goes bananas and overflows the Python stack. I guess the network of all internal references between bonds and atoms is just too complex.

**Comment by h4nsu** [comment]
Maybe just a regular ``copy.copy`` would be enough in that context?

**Comment by ridderl** [comment]
I agree, copy.copy should be sufficient.
I am thinking that
```
mol_copy = Molecule.from_dict(mol.as_dict)
```
should then be one way of copying big molecules ...

**Comment by h4nsu** [comment]
I thought about it, it's a nice "hack" :) But I think I would like to keep the possibility to copy only some part of the molecule. I'm actually rewriting ``Molecule.copy()`` now :)

**Comment by ridderl** [comment]
I checked: copy.copy works for the serialization. Would you like to make the change? (I prefer not to touch master myself :-)

**Comment by ridderl** [comment]
Hang on. It doesn't work ... Need to check why.

**Comment by ridderl** [comment]
It works after adding an extra copy of the the atom.__dict__'s and bond.__dicts__ 's. Don't ask me why :-)
