### ISSUE TITLE
Restart fails when pickling failed

### ISSUE THREAD

**Issue by ridderl** [SCM-NV/PLAMS#20]
I ran into a case where pickling of one job failed (due to `maximum recursion depth exceeded while calling a Python object`), but for all other jobs it succeeded. Restarting fails in that case as depickling the dill file is not possible. I propose to catch this error, such that the restart continues. This one job needs to be recalculated, but other results can be reused.

**Comment by h4nsu** [comment]
Sure, this seems like a very nice solution.

I'm a bit curious about some more details of this error. So did it produce a ``.dill`` file, but it was somehow corrupted and impossible to load? Maybe it would be nice to report it to ''dill people''?

**Comment by h4nsu** [comment]
A little pedantic change from my side and we're ready to merge :)

**Comment by ridderl** [comment]
I'm not able to reproduce the failure with dill anymore. Can it be that this error is solved by another fix you made recently? It did generate a `.dill`, but it was almost empty. In any case, it won't hurt to implement this catch.
