### ISSUE TITLE
_full_runscript bug

### ISSUE THREAD

**Issue by LaTruelle** [SCM-NV/PLAMS#23]
The following script does not work as it should, 

```
from scm.plams import *
import os

init()

myMol = Molecule('NBO.xyz')

settings = Settings()
settings.input.XC.GGA = 'BLYP'
settings.input.BASIS.type = 'DZP'

myJob = ADFJob(molecule=myMol, settings=settings)

@add_to_class(ADFJob)
def postrun(self):
        ret = os.system(""" "$ADFBIN/adfnbo" << eor
        write
        spherical
        nbo-analysis
        eor

        "$ADFBIN/gennbo6" FILE47

        "$ADFBIN/adfnbo" <<eor
        spherical
        fock
        read
        end input
        eor
        """)
        return

print(myJob.get_runscript())
print(myJob.get_input())
print(myJob._full_runscript())

myJob.run()

finish()
```

The last `print` statement returns:

```
[17:44:49] PLAMS working folder: /home/enicolas/test/plams.12752
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    print(myJob._full_runscript())
  File "/sara/sw/adf2017.103/scripting/plams/src/scm/plams/core/basejob.py", line 347, in _full_runscript
    ret = self.settings.runscript.shebang +'\n\n'
  File "/sara/sw/adf2017.103/scripting/plams/src/scm/plams/core/settings.py", line 262, in merge
    ret.soft_update(other)
  File "/sara/sw/adf2017.103/scripting/plams/src/scm/plams/core/settings.py", line 205, in soft_update
    if isinstance(other[name], Settings):
TypeError: string indices must be integers
```

Any idea?

**Comment by h4nsu** [comment]
Hi, thanks for the report and for your interest in PLAMS.

It's not really a bug. `_full_runscript()` is a private method for a reason, it requires some things to happen before it can be safely called. `_full_runscript()` assumes that job's `settings` has already been updated with default settings form `config.job` and uses entries from there (like `self.settings.runscript.shebang`).

So the answer is: please don't use it, use `get_runscript()` instead. If, for some reason, you have to use 
`_full_runscript()`, please do it after running a job. If you really, really have to do it before, simply do `myJob.settings.soft_update(config.job)` first.

If you would like to peek how exactly your runscripts will look like before starting actual calculations, you can run PLAMS in preview mode (`config.preview = True`). That way only inputs and runscripts are produced, nothing is executed.

A little suggestion about the code you posted: there's much more natural way to do what you did in `postrun()`. If you wish to run some bash commands after the main jobfinished, you can simply append them to the actual runscript:
```python
myJob.settings.runscript.post = """ "$ADFBIN/adfnbo" << eor
write
spherical
nbo-analysis
eor

"$ADFBIN/gennbo6" FILE47

"$ADFBIN/adfnbo" <<eor
spherical
fock
read
end input
eor"""
```

**Comment by LaTruelle** [comment]
Thanks for the answers, it makes sense indeed, and your suggestion for including the postrun code is much easier to use rather than using decorators.
