### ISSUE TITLE
No selftests for PLAMS ?

### ISSUE THREAD

**Issue by miroi** [SCM-NV/PLAMS#25]
Guys,

don't you plan to add some self-tests of the library ? 

Something what would test preparing inputs and extracting data from ADF, DIRAC outputs.

**Comment by h4nsu** [comment]
Yes, this is a major issue on our TODO list. If you have any example quick calculations which you think would work good for testing purposes, feel free to share them :)

**Comment by felipeZ** [comment]
We also have another library that uses **Plams** on the background, is it called [QMWorks](https://github.com/SCM-NV/qmworks)

**Comment by miroi** [comment]
Aaaah, som QMWorks contains tests on DIRAC I was looking for. Good. Closing this issue.
