### ISSUE TITLE
Again Not Running with Python <3.6

### ISSUE THREAD

**Issue by patrickmelix** [SCM-NV/PLAMS#54]
Hey,

you included multiple strings with the new [PEP 498](https://www.python.org/dev/peps/pep-0498/#examples-from-python-s-source-code) of Python 3.6 (`f"some string with {var}"`). If you want to enforce the latest python, please update the documentation. Older versions obviously fail.

Same discussion as in #52 ...

Cheers,
Patrick

**Comment by rlKoekie** [comment]
Sounds to me like Michal should downgrade his python version ;-)

**Comment by h4nsu** [comment]
I'm not doing it on purpose, Python 3.6 was released in 2016... Time to update, sorry

**Comment by patrickmelix** [comment]
Ok, I strongly disagree but of course your choice.
HPC Systems are very slow in updating their stuff because reliability is most important to them. So on many of those you are not able to use PLAMS anymore. Especially annoying since its not a real feature you introduce here, just fancy string-formatting that can be done with 3.5 too.
And yes, sometimes you can install your own python but it is still super annoying for users.

**Comment by h4nsu** [comment]
Well, all your arguments are kinda true, but on the other hand we (SCM) ship our own Python 3.6 with all the dependencies and useful tools, preconfigured to run PLAMS. So it's always there and available. Why insist on using your own Python?

**Comment by patrickmelix** [comment]
* Because I want to use modules that are not available in the SCM Python.
* I use more than one SCM release by loading modules (I think many people do).
* I want to use recent PLAMS functionality with SCM releases.

**Comment by h4nsu** [comment]
> Because I want to use modules that are not available in the SCM Python.
But you still can do it! You can install any package inside SCM Python just like you would install it on any other Python, we ship the recent `pip`. Or, if you don't have the rights to write in the folder where SCM Python is, you can just put a package in your /home and use `$SCM_PYTHONPATH` to point to it.
> I use more than one SCM release by loading modules (I think many people do).
Why would you ever like to do it? O_o
> I want to use recent PLAMS functionality with SCM releases.
You can do all the things you mentioned BOTH with SCM Python and with your own Python. It's just about making small adjustments in your environment or using virtual environments. If you're enough of an expert user to juggle different ADF releases, you're smart enough to set environmental variable ;)

**Comment by patrickmelix** [comment]
As I see and use PLAMS as a standalone code I am just not willing to handle yet another Python environment and concern myself with all this. Of course you're right, I could do all that. But I don't want to.

I think we both made our point, lets leave it at that :wink:
