### ISSUE TITLE
energy['cm-1'] missing from scm.plams.tools.units

### ISSUE THREAD

**Issue by BvB93** [SCM-NV/PLAMS#55]
The [documentation](https://www.scm.com/doc/plams/components/utils.html#units) claims that both 'cm^-1' and 'cm-1' are valid energy units, yet only 'cm^-1' is defined in [scm.plams.tools.units](https://github.com/SCM-NV/PLAMS/blob/3f889572e0eff55d2379bb17ff7141a96896a622/tools/units.py#L96) .

**Comment by h4nsu** [comment]
Fixed! Thanks!
