### ISSUE TITLE
plams_defaults

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/PLAMS#6]
The user that are not using all the SCM scripting environment can install _Plams_ from github like:
`pip install https://github.com/SCM-NV/plams/tarball/master#egg=plams --upgrade`
For instance, this is the way that is installed in [qmworks](https://github.com/SCM-NV/qmworks).

Problem is that the user must defined the `PLAMSDEFAULTS` environmental variable pointing to the 
[plams_defaults](https://github.com/SCM-NV/PLAMS/blob/master/utils/plams_defaults.py) module. This module is not in include in the installation. 

Therefore I proposed to include this module inside the folder containing the source code.

**Note**: Of course the user can clone the repo, but remember that most of our user are non-programmers.

**Comment by felipeZ** [comment]
see [commit](https://github.com/SCM-NV/PLAMS/commit/63a9857a6ceb114231875ad37d71c219c71c167c).

**Comment by felipeZ** [comment]
A second alternative could be to install plams like: 
``pip install -e git://github.com/SCM-NV/plams.git@master#egg=plams``

Then export  the environmental variable like:
  ``echo 'export PLAMSDEFAULTS=$HOME/src/plams/utils/plams_defaults.py' >> $HOME/miniconda/envs/qmworks/bin/activate``

But it is error prone

**Comment by h4nsu** [comment]
This is really a good point and I like this change. $PLAMSDEFAULTS was supposed to be a trick for advanced users, who would like to have different "profiles" defined with different versions od `plams_defaults.py` and quickly switch between them without having to edit any files.

However, I don't see why we need to move it inside `src` folder. The standard "user installation", no matter if done via SCM Suite or any other way, should contain the `utils` folder. Is it not possible to set up via pip?(sorry for a stupid question, don't have much experience with that).
