### ISSUE TITLE
Feature Request: Providing DOI for referencing (e.g. via Zenodo)

### ISSUE THREAD

**Issue by patrickmelix** [SCM-NV/PLAMS#65]
Hey,

I would suggest linking this project to [Zenodo](https://zenodo.org/) so that users can cite the Software. The automatic release-upload of Zenodo will allow users to cite specific versions and should keep work for maintainers at a minimum.

Cheers,
Patrick

**Comment by h4nsu** [comment]
I am well aware of Zenodo and would be happy to use it, but it's not my decision. Try writing an email to Stan.
