### ISSUE TITLE
"C-Mat" Not recognized...

### ISSUE THREAD

**Issue by complext** [SCM-NV/PLAMS#70]
Hi all, 

Version: **ADF 2018.103**
Issue: "C-Mat", "C-MATRIX", "C-MAT" not recognized by PLAMS engine
Instance: When I have the line
`job.settings.input.SOLVATION.CMat = 'POT'` (line 25)

I get as failure reason in the .out file for any given simulation from ADF:
````
 *******************************************************************************

 ADF EXIT called
 Input error: Unrecognized keyword 'cmat' in block 'solvation'
Similar valid keywords:
-  'c-mat' in block 'solvation'
````

When I switch to using something like "C-MAT" or "c-mat", my PLAMS script fails in the Python compiler, returning the following traceback:
`
Execution interrupted by the following exception:
SyntaxError: can't assign to operator (input, line 25)
`
Please describe, or document at least, how you are supposed to call the C-MATRIX computation method under COSMO solvation settings. Thank you.

**Comment by patrickmelix** [comment]
Problem is, that the dot-notation only works without special characters. Just use the dict-notation like
```
job.settings.input.solvation['c-mat'] = 'POT'
```
This should fix the problem.

**Comment by complext** [comment]
Hi, 

Apparently it did not fix it, I corrected it so that my Pythonic script looks like (for the entire "SOLVATION" block in the ADF runtime script):


`    job.settings.input.SOLVATION.Surf = 'Delley'
    job.settings.input.SOLVATION.Solvent = 'Water'
    job.settings.input.SOLVATION.cav0 = '0.0'
    job.settings.input.SOLVATION.cav1 = '0.0067639'
    job.settings.input.SOLVATION.Charged = 'CONJ'
    job.settings.input.SOLVATION['c-mat'] = 'POT'
    job.settings.input.SOLVATION.SCF = 'VAR ALL'
    job.settings.input.SOLVATION.CSMRSP
`

Yet my output from ADF is (as the run crashes promptly within a minute of job submittal):
````
 *******************************************************************************

 ADF EXIT called
 Input error: Unrecognized keyword 'subend' in block 'solvation'


 *******************************************************************************
 *******************************************************************************
````
Please help, it will be much appreciated.
