### ISSUE TITLE
How to include dependencies...

### ISSUE THREAD

**Issue by complext** [SCM-NV/PLAMS#71]
Hello all,

I do not see this documented, but how would I go about including a dependency file in a PLAMS script? For example, I have posted the run script below from an ADF 2018 simulation.

````
#! /bin/sh

# dependency: ".minus" ".minus.t21"
# dependency: ".plus" ".plus.t21"
"$ADFBIN/adf" <<eor
:: # dependency: ".minus" ".minus.t21"
:: # dependency: ".plus" ".plus.t21"
GUIBONDS
END

SYMMETRY NOSYM

BASIS
type DZ
core Large
createoutput None
END

NOPRINT LOGFILE
BADER ENERGY Reactivity 

AROMATICITY
END
TOTALENERGY
EXTENDEDPOPAN

eor

"$ADFBIN/adfreport" ".t21" fukui-minus-plus-bader
````

How would I include the above "#" dependencies? As environment variables in the batch script that calls the PLAMS Pythonic script? Or in the PLAMS Pythonic script itself?

Thank you.

**Comment by h4nsu** [comment]
These dependencies are relevant only for the graphical user interface. ADF binary ignores them (that's why they're in comments). Unless you specifically want to use PLAMS to mimic GUI functionality, I would just forget about those lines. You probably don't need them.
