### ISSUE TITLE
Plams can't read PDB files

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/PLAMS#8]
There are several problems with the *PDB reader* of Plams:
  * It does not follow the PDB conventions about the cartesian coordinates, see the [Atom](http://www.bmrb.wisc.edu/standards/pdb_3-3_atom_record_example.pdf) field record. Plams is reading the wrong columns.
  * The element type may not exist.

**Comment by h4nsu** [comment]
While writing the PDB reader I was using the official format specification:
ftp://ftp.wwpdb.org/pub/pdb/doc/format_descriptions/Format_v33_A4.pdf

The problem is that not all the PDB files follow the rules specified there :(

Could you maybe give an example of a file that does not work properly?

**Comment by felipeZ** [comment]
See for instance the attach file [test.txt](https://github.com/SCM-NV/PLAMS/files/616435/test.txt).
I changed the format to .txt because it is not possible to attach it as .pdb

**Comment by h4nsu** [comment]
Ad 1. This I don't understand. Coordinates are meant to be in, respectively, 31-38, 39-46 and 47-54 and this is where PLAMS is reading from...

Ad 2. Yeah, according to the format and the file you linked in the first post, atomic symbol should be in columns 77-78. Columns 13-16 are meant for atom "name" which is the force-field-style type of atom. Is there a way of deducing a symbol from that name in a reliable way (other than hardcoding the entire mapping?). Columns 13-14?

**Comment by felipeZ** [comment]
That's the output of a widely used package in Molecular dynamics and RDKit is able to read it. Problem is that the Coordinates on Column 77-78 are no mandatory and I do not see a sensible way to get the atomic symbols from the atomic names.

**Comment by h4nsu** [comment]
"The element symbol is always present on each ATOM record; charge is optional." - PDB format definition
"Screw that!" - widely used MD package author ;P

I can implement a workaround that should be a bit more robust: if symbol is not present in 77-78, try to obtain it from 13-14. I found some info on the web that it should contain the atomic symbol (also the file you attached indicates that - compare carbon and magnesium atoms there)

What about these coordinates being read improperly?

**Comment by h4nsu** [comment]
[Solution?](https://github.com/SCM-NV/PLAMS/tree/pdbread)

**Comment by felipeZ** [comment]
I don't understand how PLams read the x, y, z coordinates. According to the the definition of `readpdb` in Plams:

```python
    def readpdb(self, f, frame):
        pdb = PDBHandler(f)
        models = pdb.get_models()
        if frame > len(models):
            raise MoleculeError('readpdb: There are only %i frames in %s' % (len(models), f.name))

        for i in models[frame-1]:
            if i.name in ['ATOM  ','HETATM']:
                x = float(i.value[0][24:32])
                y = float(i.value[0][32:40])
                z = float(i.value[0][40:48])
                atnum = PT.get_atomic_number(i.value[0][70:72].strip())
                self.add_atom(Atom(atnum=atnum,coords=(x,y,z)))

        return pdb
```

**Comment by felipeZ** [comment]
What Would happen with names like `CGA` ?

**Comment by h4nsu** [comment]
Names like that occupy columns 14-16, so taking symbol from 13-14 works fine.

And again - what's the problem with coordinates?

**Comment by felipeZ** [comment]
There was not a problem with the coordinates, it was a problem counting from zero instead of 1.

**Comment by h4nsu** [comment]
But does it work correctly or not?

**Comment by felipeZ** [comment]
Not, it does not solve the problem. RDKit can read the file that I send you but Plams can't.

**Comment by h4nsu** [comment]
Yyy, I just tried and it seems to work... Can you be a bit more specific?

**Comment by felipeZ** [comment]
I'm using python3.5 and the error is the following:
```python
mol = plams.Molecule(filename='test.pdb')
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/Users/felipe/miniconda3/envs/qmworks/lib/python3.5/site-packages/plams/basemol.py in read(self, filename, inputformat, frame)
   1338                 with open(filename, 'rU') as f:
-> 1339                     ret = self._readformat[inputformat](self, f, frame)
   1340             except:

/Users/felipe/miniconda3/envs/qmworks/lib/python3.5/site-packages/plams/basemol.py in readpdb(self, f, frame)
   1289     def readpdb(self, f, frame):
-> 1290         pdb = PDBHandler(f)
   1291         models = pdb.get_models()

/Users/felipe/miniconda3/envs/qmworks/lib/python3.5/site-packages/plams/pdbtools.py in __init__(self, textfile)
     67         if textfile is not None:
---> 68             if isinstance(textfile, file):
     69                 self.read(textfile)

NameError: name 'file' is not defined

During handling of the above exception, another exception occurred:

FileError                                 Traceback (most recent call last)
<ipython-input-9-9186970ea04c> in <module>()
----> 1 mol = plams.Molecule(filename='test.pdb')

/Users/felipe/miniconda3/envs/qmworks/lib/python3.5/site-packages/plams/basemol.py in __init__(self, filename, inputformat, geometry, **other)
    382 
    383         if filename is not None :
--> 384             self.read(filename, inputformat, geometry)
    385 
    386 

/Users/felipe/miniconda3/envs/qmworks/lib/python3.5/site-packages/plams/basemol.py in read(self, filename, inputformat, frame)
   1339                     ret = self._readformat[inputformat](self, f, frame)
   1340             except:
-> 1341                 raise FileError('read: Error reading file %s' % filename)
   1342             return ret
   1343         else:

FileError: read: Error reading file test.pdb
```

**Comment by h4nsu** [comment]
OK, nice catch. Apparently "file" is no longer a built-in type in Python 3 and this is the cause of the break, not that particular pdb file. But it also means it is currently impossible to read ANY pdb file in Python 3. Is this really the first and the only you tried? O_o

**Comment by felipeZ** [comment]
I have been using only `xyz` format so far, but now we are doing some classical dynamics packages that output pdb. Also, Lars uses `pdb` files but he manipulates them with RDKit.

**Comment by h4nsu** [comment]
Should be fine now. Sorry for that, I must have missed that while porting to Py2+3 compatible version. Thanks for the report!

Please let me know if there are still some problems with PDB reader.
