### ISSUE TITLE
Allow multiple CP2K executables

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/PLAMS#82]
Currently, `cp2k.popt` is used for running CP2K. It would be great if the user can optionally pick another executable [from the available binaries](https://github.com/cp2k/cp2k/blob/master/INSTALL.md#3-compile)

**Comment by h4nsu** [comment]
@felipeZ I assume I can close this issue now, right?

**Comment by felipeZ** [comment]
Sorry, I forgot to close it!
