### ISSUE TITLE
Allow case sensitive Settings

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/PLAMS#92]
In CP2K is quite common to have exactly the same keyword with different values, for example:
```
    &KIND  C
      BASIS_SET  DZVP-MOLOPT-SR-GTH-q4
      BASIS_SET  AUXFIT CFIT3
      POTENTIAL  GTH-PBE-q4
    &END
```

Previous versions of the settings class allow to bypass this problem by using the following notation:
```python
s = Settings()
s.kind.C.BASIS_SET = "DZVP-MOLOPT-SR-GTH-q4"
s.kind.C.basis_set = "AUXFIT CFIT3"
```
Case sensitive `basis_set` used to produced the desired results. Would it be possible to reintroduced this behavior?

**Comment by BvB93** [comment]
The old behaviour can be replicated in this case by passing the basis set as a list of strings:

``` python
from scm.plams import Settings

s = Settings()
s.input.kind.C.potential = 'GTH-PBE-q4'
s.input.kind.C.basis_set = ['DZVP-MOLOPT-SR-GTH-q4', 'AUXFIT CFIT3']
```

The output:
```
&KIND  C
  BASIS_SET  DZVP-MOLOPT-SR-GTH-q4
  BASIS_SET  AUXFIT CFIT3
  POTENTIAL  GTH-PBE-q4
&END
```

**Comment by felipeZ** [comment]
solved by @BvB93  comment
